### ISSUE TITLE
KeyError: 'count_k'

### ISSUE THREAD

**Issue by Patrickpwq** [jncraton/doctestfn#1]
Hi ! I had problems when executing doctestfn, here is my code and the command that I typed in.

```python
#a single function file(test.py) without any other content
def count_k(n, k):
    """ Counts the number of paths up a flight of n stairs
    when taking up to and including k steps at a time.
    >>> count_k(3, 3) # 3, 2 + 1, 1 + 2, 1 + 1 + 1
    4
    >>> count_k(4, 4)
    8
    >>> count_k(10, 3)
    274
    >>> count_k(300, 1) # Only one step at a time
    1
    """
    if n < 0:
        return 0
    if n == 0:
        return 1
    if n == 1:
        return 1
    if n == 2:
        if k == 1:
            return 1
        else:
            return 2

    tot = 0
    for i in range(1, k + 1):
        tot += count_k(n - i, k)

    return tot
```

```powershell
PS D:\Desktop\cs61a\lab\lab04> doctestfn test.py count_k
Traceback (most recent call last):
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\Scripts\doctestfn.exe\__main__.py", line 7, in <module>
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\doctestfn\doctestfn.py", line 31, in main
    doctest.run_docstring_examples(globals()[args.function], globals(), verbose=args.verbose)
KeyError: 'count_k'
```

Wondering where is the problem, thanks!

**Comment by jncraton** [comment]
This is because [this test module](https://docs.python.org/3/library/test.html) is being imported rather than your local `test` module as you are expecting. You should be able to work around this by naming your module something else. Your example code works for me if I rename `test.py` to `stairs.py`.

**Comment by Patrickpwq** [comment]
Thanks!
